apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cortex
  annotations:
    version: "1.11-22.04_beta"
    description: "Cortex is an open-source platform for building horizontally scalable, multi-tenant, and long-term storage for Prometheus metrics."
spec:
  components:
    - name: cortex
      type: webservice
      properties:
        image: ubuntu/cortex:1.11-22.04_beta
        imagePullPolicy: Always
        env:
          - name: TZ
            value: "UTC"
        ports:
          - port: 9009
            expose: true
        cpu: "200m"
        memory: "256Mi"
      traits:
        - type: napptive-ingress
          properties:
            name: cortex-client
            port: 9009
            path: /
            rewritePath: /
        - type: storage
          properties:
            configMap:
              - name: cortex-cm
                mountPath: /etc/cortex/cortex.yaml
