apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: prometheus
  annotations:
    version: "latest"
    description: "Prometheus is a systems and service monitoring system"
spec:
  components:
    - name: prometheus
      type: webservice
      properties:
        image: prom/prometheus:latest
        ports:
            - port: 9090
              expose: true
        cpu: "200m"
        memory: "256Mi"
      traits:
        - type: napptive-ingress
          properties:
            name: prom-server
            port: 9090
            path: /
            rewritePath: /
        - type: storage
          properties:
            configMap:
              - name: prom-cm
                mountOnly: false
                mountPath: /etc/prometheus

