apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: redis
  annotations:
    version: "5.0.7"
    description: "Redis in-memory data structure store"
spec:
  components:
    - name: redis
      type: statefulservice
      properties:
        image: redis:5.0.7
        replicas: 1
        ports:
          - port: 6379
            expose: true
        cpu: "200m"
        memory: "256Mi"
      traits:
        - type: storage
          properties:
            emptyDir:
              - name: redis-data
                mountPath: /redis-master-data
            configMap:
              - name: config
                mountPath: /redis-master
                mountToEnv: # mount to Environment variables (inly one variable, uses mountToEnvs it there is more than one)
                  configMapKey: redis-config # cm key
                data: # (Optional) if the cm is going to be created, data field contains the cm data
                  redis-config: "" # key - value data

