apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: redis
  annotations:
    version: "5.0.7"
    description: "Redis in-memory data structure store"
spec:
  components:
    - name: redis
      type: statefulservice
      properties:
        image: redis:5.0.7
        replicas: 1
        ports:
          - port: 6379
            expose: true
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
      traits:
        - type: storage
          properties:
            ConfigMap:
              


